### ISSUE TITLE
My Breaking In research

### ISSUE THREAD

**Issue by digininja** [gradiuscypher/infosec_getting_started#2]
This is a bit old now but quite a bit of it is still relevant I think.

https://digi.ninja/projects/breaking_in_part_1.php

**Comment by gradiuscypher** [comment]
Thanks, I'll check it out :)

**Comment by gradiuscypher** [comment]
@digininja - I've added the content to the new formatting. Thanks for the link! :)

**Comment by gradiuscypher** [comment]
For full followup, the content can be found here:
https://github.com/gradiuscypher/infosec_getting_started/blob/master/how_to_start/README.md
