### ISSUE TITLE
Recommend lockpicking/bypasses as an additional interest

### ISSUE THREAD

**Issue by calebwatt15** [gradiuscypher/infosec_getting_started#3]
As the title states. You see lock picking at most cons now, and TOOOL or Lock sport meetups in most major cities, attended by local hackers. I'd recommend adding this as an category under  the Interests sections. If you would like, I can even add a bunch of links, etc to my fork and make the pull request.

**Comment by gradiuscypher** [comment]
Sounds good, and I totally agree that it's often an interest that the security industry dabbles in. Working on pulling in a few PRs with respect to formatting, but feel free to add any info you have after that's done :)

**Comment by gradiuscypher** [comment]
@calebwatt15 - Formatting changes have been pulled in, feel free to toss some helpful links into the "misc" section and I'll review!

https://github.com/gradiuscypher/infosec_getting_started/blob/master/misc/README.md

**Comment by calebwatt15** [comment]
Done, please see pull request #8

**Comment by gradiuscypher** [comment]
This has been resolved via pull request #8 

Thanks again!
