### ISSUE TITLE
Hiring

### ISSUE THREAD

**Issue by markofu** [gradiuscypher/infosec_getting_started#6]
I recommend that you do a section on hiring:

- do's and don'ts on both sides
- sample questions maybe
- resources for preparation

**Comment by calebwatt15** [comment]
Gradius, would hiring be under misc? or a new folder unto itself? I've got at least 1 resource for sample questions in mind.

**Comment by gradiuscypher** [comment]
@calebwatt15 I'd likely toss that under misc for now :)
